import { Action, IResourceItem } from "@refinedev/core";

interface CustomTitleHandlerProps {
  resource?: IResourceItem;
  action?: Action;
  params?: Record<string, string>;
  pathname?: string;
  autoGeneratedTitle: string;
}

export const customTitleHandler = ({
  resource,
  action,
  params,
  pathname,
  autoGeneratedTitle,
}: CustomTitleHandlerProps) => {
  let title = process.env.NEXT_PUBLIC_APP_NAME;

  if (action && resource) {
    title = `${resource.meta.label} ${title ? `| ${title}` : ""}`;
  }

  return title ?? autoGeneratedTitle;
};
